export const THEME = {
  DANGER_COLOR: `#e53935`,
  GREY_COLOR: `#757575`,
  TEXT_COLOR: `#468769`,
  MAIN_COLOR: `#3b727d`,
  WHITE: `white`,
  EDIT_COLOR: `whitesmoke`,
  EDIT_BUTTON_COLOR: `tan`,
  PADDING_HORIZONTAL: 30,
  PADDING_VERTICAL: 20,
};
